"""Add file_id to files table

Revision ID: 10620181061a
Revises: dcdfc5212d26
Create Date: 2024-11-21 15:45:26.344306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10620181061a'
down_revision: Union[str, None] = 'dcdfc5212d26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uniq_file_project_file_id', ['project_id', 'file_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint('uniq_file_project_file_id', type_='unique')
        batch_op.drop_column('file_id')

    # ### end Alembic commands ###
