"""Add unique index to history_full

Revision ID: 12543e31909d
Revises: 682ccedc668e
Create Date: 2025-01-12 14:23:18.579118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12543e31909d'
down_revision: Union[str, None] = '682ccedc668e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history_full', schema=None) as batch_op:
        batch_op.create_unique_constraint('uniq_history_full_project_id', ['project_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history_full', schema=None) as batch_op:
        batch_op.drop_constraint('uniq_history_full_project_id', type_='unique')

    # ### end Alembic commands ###
