"""change file.visible to hidden

Revision ID: 20f926391927
Revises: 3eac45006a09
Create Date: 2024-12-01 20:47:58.617841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20f926391927'
down_revision: Union[str, None] = '3eac45006a09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=True))
        batch_op.drop_column('visible')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible', sa.BOOLEAN(), server_default=sa.text("'t'"), nullable=True))
        batch_op.drop_column('hidden')

    # ### end Alembic commands ###
