"""Add tag to users_roles mapping

Revision ID: 26b621efd371
Revises: b1663aae2f01
Create Date: 2024-12-14 13:32:11.384290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26b621efd371'
down_revision: Union[str, None] = 'b1663aae2f01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('uniq_users_roles_user_classroom_project_role', type_='unique')
        batch_op.create_unique_constraint('uniq_users_roles_user_classroom_project_role_tag', ['user_id', 'classroom_id', 'project_id', 'role_id', 'tag_id'])
        batch_op.create_foreign_key('fk_users_roles_tag_id', 'tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_roles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_roles_tag_id', type_='foreignkey')
        batch_op.drop_constraint('uniq_users_roles_user_classroom_project_role_tag', type_='unique')
        batch_op.create_unique_constraint('uniq_users_roles_user_classroom_project_role', ['user_id', 'classroom_id', 'project_id', 'role_id'])
        batch_op.drop_column('tag_id')
    # ### end Alembic commands ###
