"""setup inheriting and configuring files

Revision ID: 3eac45006a09
Revises: 10620181061a
Create Date: 2024-12-01 20:42:25.229019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eac45006a09'
down_revision: Union[str, None] = '10620181061a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_file_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('readonly', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('inherited', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('visible', sa.Boolean(), server_default='t', nullable=True))
        batch_op.create_foreign_key('fk_files_parent_file_id', 'files', ['parent_file_id'], ['id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_projects_parent_id', 'projects', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projects_parent_id', type_='foreignkey')
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint('fk_files_parent_file_id', type_='foreignkey')
        batch_op.drop_column('visible')
        batch_op.drop_column('inherited')
        batch_op.drop_column('readonly')
        batch_op.drop_column('parent_file_id')

    # ### end Alembic commands ###
