"""Add creation time to tags

Revision ID: 47721c54b493
Revises: faffb45d0dcc
Create Date: 2025-01-25 13:17:19.230783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47721c54b493'
down_revision: Union[str, None] = 'faffb45d0dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.Integer(), nullable=True))

    with op.batch_alter_table('projects_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects_tags', schema=None) as batch_op:
        batch_op.drop_column('created')

    with op.batch_alter_table('classrooms_tags', schema=None) as batch_op:
        batch_op.drop_column('created')
    # ### end Alembic commands ###
