"""Add display option on tags

Revision ID: 533e2439a022
Revises: aa21e01c87cc
Create Date: 2025-02-05 21:45:47.637100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '533e2439a022'
down_revision: Union[str, None] = 'aa21e01c87cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms_tags', schema=None) as batch_op:
        batch_op.drop_column('value')

    # ### end Alembic commands ###
