"""Add value column to tags

Revision ID: 670d1d79f226
Revises: 41340ba3622c
Create Date: 2025-01-31 22:01:46.348649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670d1d79f226'
down_revision: Union[str, None] = '41340ba3622c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects_tags', schema=None) as batch_op:
        batch_op.drop_column('value')

    # ### end Alembic commands ###
