"""unique constraint on roles_permissions

Revision ID: 90c81eeaf2c5
Revises: b4029d4b1067
Create Date: 2024-12-10 17:21:33.669271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c81eeaf2c5'
down_revision: Union[str, None] = 'b4029d4b1067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles_permissions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uniq_roles_permissions_role_id_permission_id', ['role_id', 'permission_id'])

    with op.batch_alter_table('users_roles', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_users_roles_classroom_id', 'classrooms', ['classroom_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_roles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_roles_classroom_id', type_='foreignkey')

    with op.batch_alter_table('roles_permissions', schema=None) as batch_op:
        batch_op.drop_constraint('uniq_roles_permissions_role_id_permission_id', type_='unique')

    # ### end Alembic commands ###
