"""Add detail column for permisisons to uniqueness constraint

Revision ID: 98fad63597ce
Revises: 24aba5776eb2
Create Date: 2025-02-25 17:30:50.608317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98fad63597ce'
down_revision: Union[str, None] = '24aba5776eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles_permissions', schema=None) as batch_op:
        batch_op.drop_constraint('uniq_roles_permissions_role_id_permission_id_tag_id', type_='unique')
        batch_op.create_unique_constraint('uniq_roles_permissions_role_id_permission_id_tag_id', ['role_id', 'permission_id', 'tag_id', 'detail'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles_permissions', schema=None) as batch_op:
        batch_op.drop_constraint('uniq_roles_permissions_role_id_permission_id_tag_id', type_='unique')
        batch_op.create_unique_constraint('uniq_roles_permissions_role_id_permission_id_tag_id', ['role_id', 'permission_id', 'tag_id'])

    # ### end Alembic commands ###
