"""Add classroom and project tags

Revision ID: b1663aae2f01
Revises: 90c81eeaf2c5
Create Date: 2024-12-14 13:30:08.490461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1663aae2f01'
down_revision: Union[str, None] = '90c81eeaf2c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['projects.id'], name='fk_projects_parent_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uniq_tags_name')
    )
    op.create_table('classrooms_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name='fk_classrooms_tags_classroom_id'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='fk_classrooms_tags_tag_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classroom_id', 'tag_id', name='uniq_classroomclassroomss_tago_classroom_id_tag_id')
    )
    op.create_table('projects_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_projects_tags_project_id'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='fk_projects_tags_tag_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'tag_id', name='uniq_projects_tags_project_id_tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects_tags')
    op.drop_table('classrooms_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
