"""role permissions

Revision ID: b4029d4b1067
Revises: cf255ed7e20c
Create Date: 2024-12-10 17:09:33.669271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4029d4b1067'
down_revision: Union[str, None] = 'cf255ed7e20c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_roles_permissions_role_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users_roles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_roles_classroom_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_users_roles_project_id', 'projects', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_roles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_roles_project_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_users_roles_classroom_id', 'classrooms', ['project_id'], ['id'])

    op.drop_table('roles_permissions')
    # ### end Alembic commands ###
