"""early roles

Revision ID: cf255ed7e20c
Revises: 5fa99c98e2e6
Create Date: 2024-12-08 21:33:54.790704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf255ed7e20c'
down_revision: Union[str, None] = '5fa99c98e2e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('classroom_id IS NULL OR project_id IS NULL', name='check_user_roles_classroom_nand_project'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name='fk_users_roles_classroom_id'),
    sa.ForeignKeyConstraint(['project_id'], ['classrooms.id'], name='fk_users_roles_classroom_id'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_users_roles_role_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_users_roles_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'classroom_id', 'project_id', 'role_id', name='uniq_users_roles_user_classroom_project_role')
    )
    op.drop_table('classrooms_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms_users',
    sa.Column('classroom_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name='fk_classroom_users_classroom_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_classrooms_users_user_id'),
    sa.UniqueConstraint('classroom_id', 'user_id', name='uniq_classrooms_users')
    )
    op.drop_table('users_roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
