"""add classrooms

Revision ID: dcdfc5212d26
Revises: c1ade8525879
Create Date: 2024-10-31 21:33:10.132988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcdfc5212d26'
down_revision: Union[str, None] = 'c1ade8525879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('classrooms_users',
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name='fk_classroom_users_classroom_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_classrooms_users_user_id'),
    sa.UniqueConstraint('classroom_id', 'user_id', name='uniq_classrooms_users')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classroom_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('uniq_project_owner_name', type_='unique')
        batch_op.create_unique_constraint('uniq_project_classroom_name', ['classroom_id', 'name'])
        batch_op.create_foreign_key('fk_projects_classroom_if', 'classrooms', ['classroom_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projects_classroom_if', type_='foreignkey')
        batch_op.drop_constraint('uniq_project_classroom_name', type_='unique')
        batch_op.create_unique_constraint('uniq_project_owner_name', ['owner', 'name'])
        batch_op.drop_column('classroom_id')

    op.drop_table('classrooms_users')
    op.drop_table('classrooms')
    # ### end Alembic commands ###
