"""add hacky cloned_as_assignment field to projects

Revision ID: e1fc444690ac
Revises: 16a791ed1ad4
Create Date: 2024-12-15 10:44:24.161803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1fc444690ac'
down_revision: Union[str, None] = '16a791ed1ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cloned_as_assignment', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('cloned_as_assignment')

    # ### end Alembic commands ###
